初版 訂閱折價券功能
foodaholics/Eatx6_bot pull request #9
Opened 2018-08-17 08:18 UTC by zxjte9411

d(`･∀･)b

2018-08-17 08:38 UTC, PinLin requested changes
你說還沒做完ㄉ

2018-08-20 16:12 UTC, zxjte9411 commented
# 完成了ouo

2018-08-20 19:08 UTC, PinLin reviewed
wow

2018-08-21 09:43 UTC, PinLin approved these changes
豪

2018-08-21 09:43 UTC, merged